# Generated by Django 2.1.2 on 2018-12-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=200)),
                ('block', models.CharField(max_length=200)),
                ('cluster', models.CharField(max_length=200)),
                ('gram_panchayat', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GPContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=200)),
                ('block', models.CharField(max_length=200)),
                ('cluster', models.CharField(max_length=200)),
                ('gram_panchayat', models.CharField(max_length=200)),
                ('addition', models.IntegerField()),
                ('subtraction', models.IntegerField()),
                ('multiplication', models.IntegerField()),
                ('division', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=200)),
                ('addition', models.IntegerField()),
                ('subtraction', models.IntegerField()),
                ('multiplication', models.IntegerField()),
                ('division', models.IntegerField()),
            ],
        ),
    ]
